version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - uploads:/app/uploads
      - instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped

volumes:
  uploads:
  instance: 